### ISSUE TITLE
only() in bulk sync breaks django-cacheop's post_delete logic

### ISSUE THREAD

**Issue by voron3x** [mathandpencil/django-bulk-sync#17]
Hi!

Cacheops have automatic invalidation logic by post_save signal, but with "only" chain method this logic is not working correctly (see this comment https://github.com/Suor/django-cacheops/issues/348#issuecomment-674566758).

Can i remove this method? And for "only" case we can use managed=False models with subset of fields as recommended in django doc for defer/only methods (https://docs.djangoproject.com/en/3.1/ref/models/querysets/#defer).

**Comment by ses4j** [comment]
I don't really understand what cacheops is doing to cause the problem.  I don't want to remove the `only()` unless I can replace it's functionality somehow, it's a worthwhile optimization.  

I don't use pre/post signals much (I don't like the paradigm, but I digress...).  But since bulk_create and bulk_update don't emit signals, the delete step shouldn't either.  For that reason, I should probably replace:

`objs.filter(pk__in=[_.pk for _ in list(obj_dict.values())]).delete()`

with something like `_raw_delete`: https://code.djangoproject.com/ticket/9519

That will probaly make cacheops not crash, but also break it since it depends on the hooks.  But, it probably was already broken becuase the create and update hooks aren't being invoked.

Thoughts?

**Comment by voron3x** [comment]
Yes you are correct, I need use cacheops.bulk_update for populate cache. And for these maybe best choice would be use bulk_compare with custom logic for bulk update, delete and insert. But due performance reasoning I don`t wont use compare by fields.
